/**
 * Downloads Twemoji SVGs for the picker emojis and generates assets/twemoji/emojiMap.ts
 *
 * Usage:  npx tsx scripts/generate-emoji-map.ts
 */
import * as fs from 'fs';
import * as path from 'path';
import * as https from 'https';

// All emojis from EmojiPicker categories + quick reactions
const EMOJIS = [
  // Quick reactions
  '👍','🔥','🧠','⚡','😂','❤️',
  // Smileys
  '😀','😃','😄','😁','😆','😅','🤣','😂','🙂','🙃','😉','😊','😇','🥰','😍','🤩','😘','😗','😚','😙','🥲','😋','😛','😜','🤪','😝','🤑','🤗','🤭','🤫',
  // People
  '👋','🤚','🖐','✋','🖖','👌','🤌','✌️','🤞','🤟','🤘','🤙','👈','👉','👆','🖕','👇','☝️','👍','👎','✊','👊','🤛','🤜','👏','🙌','🫶','👐','🤲','🤝',
  // Nature
  '🐶','🐱','🐭','🐹','🐰','🦊','🐻','🐼','🐨','🐯','🦁','🐮','🐷','🐸','🐵','🙈','🙉','🙊','🐔','🐧','🐦','🐤','🦆','🦅','🦉','🦇','🐺','🐗','🐴','🦄',
  // Food
  '🍎','🍊','🍋','🍇','🍓','🍈','🍒','🍑','🥭','🍍','🥥','🥝','🍅','🍆','🥑','🥦','🥬','🥒','🌽','🌶','🥕','🧄','🧅','🥔','🍠','🥐','🥯','🍞','🥖','🥨',
  // Activities
  '⚽','🏀','🏈','⚾','🥎','🎾','🏐','🏉','🥏','🎱','🏓','🏸','🏒','🥍','🏑','🏏','🥅','⛳','🏹','🎣','🤿','🥊','🥋','🎽','🛹','🛼','🛷','⛸','🤺','🏋️',
  // Travel
  '🚗','🚕','🚙','🚌','🚎','🏎','🚓','🚑','🚒','🚐','🛻','🚚','🚛','🚜','🛵','🏍','🛺','🚲','🛴','🛹','🚂','🚃','🚄','🚅','🚆','🚇','🚈','🚉','🚊','🚝',
  // Objects
  '⌚','📱','💻','🖥','🖨','⌨️','🖱','🖲','💽','💾','💿','📀','📷','📸','📹','🎥','📽','🎞','📞','☎️','📟','📠','📺','📻','🧭','⏱','⏰','⏲','⌛','⏳',
  // Symbols
  '❤️','🧡','💛','💚','💙','💜','🖤','🤍','🤎','💔','❣️','💕','💞','💓','💗','💖','💘','💝','💟','☮️','✝️','☪️','🕉','✡️','🔯','🕎','☯️','☦️','🛐','♈',
];

function emojiToCodepoint(emoji: string): string {
  return [...emoji]
    .map((c) => c.codePointAt(0)!.toString(16))
    .filter((cp) => cp !== 'fe0f')
    .join('-');
}

function fetchSvg(codepoint: string): Promise<string | null> {
  const url = `https://cdn.jsdelivr.net/gh/twitter/twemoji@latest/assets/svg/${codepoint}.svg`;
  return new Promise((resolve) => {
    https.get(url, (res) => {
      if (res.statusCode !== 200) {
        resolve(null);
        res.resume();
        return;
      }
      let data = '';
      res.on('data', (chunk: string) => (data += chunk));
      res.on('end', () => resolve(data));
    }).on('error', () => resolve(null));
  });
}

async function main() {
  // Deduplicate
  const unique = [...new Set(EMOJIS)];
  const entries: [string, string][] = [];
  let fetched = 0;

  for (const emoji of unique) {
    const cp = emojiToCodepoint(emoji);
    const svg = await fetchSvg(cp);
    fetched++;
    if (svg) {
      // Minify: collapse whitespace
      const minified = svg.replace(/\n/g, '').replace(/\s{2,}/g, ' ').trim();
      entries.push([cp, minified]);
      process.stdout.write(`\r  ${fetched}/${unique.length} fetched (${cp} OK)`);
    } else {
      process.stdout.write(`\r  ${fetched}/${unique.length} fetched (${cp} MISSING)`);
    }
  }

  console.log(`\n  Total: ${entries.length} SVGs`);

  const lines = entries.map(([cp, svg]) => `  '${cp}': '${svg.replace(/'/g, "\\'")}',`);
  const content = `// Auto-generated by scripts/generate-emoji-map.ts — DO NOT EDIT\n// Contains Twemoji SVG data for ${entries.length} emojis\n// License: CC-BY 4.0 (https://creativecommons.org/licenses/by/4.0/)\n\nexport const emojiSvgMap: Record<string, string> = {\n${lines.join('\n')}\n};\n`;

  const outPath = path.resolve(__dirname, '..', 'assets', 'twemoji', 'emojiMap.ts');
  fs.writeFileSync(outPath, content, 'utf-8');
  console.log(`  Written to ${outPath}`);
}

main().catch(console.error);
